config:
  # prefer semantic line breaks over max sentence length
  line-length: false
  # tabbed code examples violate this rule
  no-space-in-code: false
  # sometimes you gotta be hacky
  no-inline-html: false
  code-block-style: false

fix: true

globs:
  - "**.md"
ignores:
  - docs/styles