name: "🐛 Bug report"
title: "[Bug]: "
labels: [bug]
description: Please let us know about an issue you're seeing
body:
- type: markdown
  attributes: 
    value: |
      Thank you for taking the time to let us know!
- type: input
  id: jenkins-version
  attributes:
    label: Jenkins Version
    description: On what version of Jenkins did you experience this bug?
  validations:
    required: true
- type: dropdown
  id: jte-version
  attributes:
    label: JTE Version
    description: What version of JTE is installed?
    options: [ 2.5, 2.4 , 2.3, 2.2.2, 2.2.1, 2.1, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0, 1.7.1, 1.7, 1.6, 1.5.2, 1.5.1, 1.5, 1.4.2, 1.4.1, 1.4, 1.3, 1.2, 1.1.1, 1.1, 1.0 ]
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Bug Description
    description: Please describe what seems to be the problem
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  id: how-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: Please describe the minimal steps to reproduce
  validations:
    required: true
