= GitHub Organization Job

JTE can be used to apply a pipeline template to an entire GitHub Organization by creating a *GitHub Organization* job in Jenkins.

To configure this, under the *Projects* section you will set the *Project Recognizer* as `Jenkins Templating Engine`. 

== Exclude Branches Without `pipeline_config.groovy`

When `Jenkins Templating Engine` is selected, a checkbox option is presented to exclude branches in source code repositories that do not have a `pipeline_config.groovy` file at the root of the repository. 

The default value is to create pipeline jobs for every branch regardless of whether a `pipeline_config.groovy` is present or not. 

== Repository Configuration

Note, the *GitHub Organization* project can configure a *Governance Tier* for specifying pipeline templates, library sources, and applying a pipeline configuration to every branch of every repository in a GitHub Organization.

You can find these settings under the `Jenkins Templating Engine` section of the job configuration. 